name: tk_hero_chess
description: "王者荣耀小游戏“三分英雄棋”的“无尽挑战”模式的简单文字版。"
publish_to: "none"
# 手动使用时间戳作为 build-number
version: 0.1.0+20250721

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.30.1
  flame_audio: ^2.11.8
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: QingkeHuangyou
      fonts:
        - asset: assets/fonts/ZCOOLQingKeHuangYou-Regular.ttf
